### ISSUE TITLE
Not working with latest ASF build V5.2.7.4

### ISSUE THREAD

**Issue by jakey1995abc** [Sniper677/ASF_ItemDropper#8]
Here is the log I get upon starting ASF V5.2.7.4 with this plugin installed:

> 2022-06-17 18:08:40|ArchiSteamFarm-27572|INFO|ASF|InitPlugins() Initializing Plugins...
> 2022-06-17 18:08:40|ArchiSteamFarm-27572|ERROR|ASF|InitPlugins() Failed due to error: ASFItemDropper, Version=0.3.3.1, Culture=neutral, PublicKeyToken=null
> 2022-06-17 18:08:40|ArchiSteamFarm-27572|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> 
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule )
>    at System.Reflection.RuntimeModule.GetTypes()
>    at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
> System.TypeLoadException

**Comment by Ironozd** [comment]
They didn't update the plugin. Let's hope they do update.

**Comment by chuvak889** [comment]
I hope so, but it's been a while. 
I mean, i get it, they have better priorities, i just wish more programming-able people would chip in the project, it's a really useful plugin, but only for some people, so, the interest is low i guess.

**Comment by chuvak889** [comment]
Someone forked the plugin, i tried it and works perfectly with the latest ASF version.
https://github.com/chr233/ASF_ItemDropper/releases/tag/0.3.4.3

Woohoo!
